### PR TITLE
Assessment layer added

### PR DESCRIPTION
**Pull request by michaelpnelson**
link to demo deployment of your smk based app is 
 https://smk-svt-rt-b16795-dev.apps.silver.devops.gov.bc.ca

Verify that it looks good, if so merge the pull request which will trigger a prod deployment, otherwise close the pull request without merging

 mentions / notifications: @michaelpnelson, @rustyjux

### CODE REVIEW

**Comment by michaelpnelson** [comment]
The Vanity URL for the dev deploy is https://smk-svt-api-gov-bc-ca.test.api.gov.bc.ca
 

If this is a dev deploy,  verify that it looks good, then merge the pull request to trigger prod deployment.

 If this is a prod deployment, view your prod deploy at the url above :)

 mentions / notifications: @michaelpnelson, @rustyjux

**Comment by rustyjux** [comment]
Have you noticed the performance issues on the ArcGIS layer? I'm not sure if restricting the visible scale is possible or desirable but the ArcGIS layer loads slowly for me and causes my browser to lag when panning (especially at lower zoom). Meanwhile WMS is always smooth, with just some short load times when panning (it seems like it doesn't cache at all, whereas ArcGIS does).

(btw, a better term might be ArcGIS Map Service - a Feature Service would be a little different so calling it 'ArcGIS Feature' is confusing - see https://support.esri.com/en-us/knowledge-base/faq-what-is-the-difference-between-a-map-service-featur-000027304#:~:text=A%20map%20service%20does%20not,attributes%20of%20a%20feature%20service.)

**Comment by michaelpnelson** [comment]
The Vanity URL for the dev deploy is https://smk-svt-api-gov-bc-ca.test.api.gov.bc.ca
 

If this is a dev deploy,  verify that it looks good, then merge the pull request to trigger prod deployment.

 If this is a prod deployment, view your prod deploy at the url above :)

 mentions / notifications: @michaelpnelson, @rustyjux

**Comment by michaelpnelson** [comment]
The Vanity URL for the dev deploy is https://smk-svt-api-gov-bc-ca.test.api.gov.bc.ca
 

If this is a dev deploy,  verify that it looks good, then merge the pull request to trigger prod deployment.

 If this is a prod deployment, view your prod deploy at the url above :)

 mentions / notifications: @michaelpnelson, @rustyjux

**Comment by michaelpnelson** [comment]
The Vanity URL for the dev deploy is https://smk-svt-api-gov-bc-ca.test.api.gov.bc.ca
 

If this is a dev deploy,  verify that it looks good, then merge the pull request to trigger prod deployment.

 If this is a prod deployment, view your prod deploy at the url above :)

 mentions / notifications: @michaelpnelson, @rustyjux

**Comment by michaelpnelson** [comment]
The Vanity URL for the dev deploy is https://smk-svt-api-gov-bc-ca.test.api.gov.bc.ca
 

If this is a dev deploy,  verify that it looks good, then merge the pull request to trigger prod deployment.

 If this is a prod deployment, view your prod deploy at the url above :)

 mentions / notifications: @michaelpnelson, @rustyjux

**Comment by michaelpnelson** [comment]
The Vanity URL for the dev deploy is https://smk-svt-api-gov-bc-ca.test.api.gov.bc.ca
 

If this is a dev deploy,  verify that it looks good, then merge the pull request to trigger prod deployment.

 If this is a prod deployment, view your prod deploy at the url above :)

 mentions / notifications: @michaelpnelson, @rustyjux

**Comment by michaelpnelson** [comment]
link to demo deployment of your smk based app is 
 https://smk-svt-rt-b16795-prod.apps.silver.devops.gov.bc.ca

Verify that it looks good, if so merge the pull request which will trigger a prod deployment, otherwise close the pull request without merging

 mentions / notifications: @michaelpnelson, @rustyjux

**Comment by michaelpnelson** [comment]
The Vanity URL for the prod deploy is https://smk-svt.api.gov.bc.ca
 

If this is a dev deploy,  verify that it looks good, then merge the pull request to trigger prod deployment.

 If this is a prod deployment, view your prod deploy at the url above :)

 mentions / notifications: @michaelpnelson, @rustyjux

**Pull request merged**
